#!/bin/bash
PROGRAM=$(basename $0)
VERSION="0.0.1"

## Testing the best opt script to define the operation of build4repo
pushRepo=0
noConfirm=''

version_info() {
    echo -e "\n$0 $VERSION - Matthew Phillip Cooper"
}

##  Help screen
help_me() {
    version_info
    cat <<EOT
    Usage: $PROGRAM <-y or -n> <-c>
        -y to rebuild the repo database.
        -n to not rebuild the repo database.
        -c to add the noconfirm flag to makepkg and auto-continue.
        -v to display version information
        -h to view this help screen
    If used with no option then it will prompt you for eveything.
EOT
}

##  New section that accepts args -y and -n for yes and no, and -c for --noconfirm
while getopts "ynchv" option; do
    case $option in
    y)
        pushRepo=2
        ;;

    n)
        pushRepo=1
        ;;
    c)
        noConfirm='--noconfirm'
        ;;
    h)
        help_me
        exit 3
        ;;
    v)
        version_info
        exit 3
        ;;
    ?)
        help_me
        exit 1
        ;;
    esac
done

echo "Push to repo = $pushRepo"
if [[ "$noConfirm" != '' ]]; then
    echo "Confirmation: $noConfirm"
fi
exit 0
